name: Build containers

on: [push]

defaults:
    run:
        shell: bash -l {0}

jobs:
    build:
        name: Build containers
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - name: login to GitHub Container Registry
              uses: docker/login-action@v1
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Determine version
              run: echo "DATESTAMP_VERSION=$(date +%F)" >> $GITHUB_ENV

            - name: Build docker
              run: |
                  cd docker && docker build \
                        -t ghcr.io/${{ github.actor }}/devstack:latest \
                        -t ghcr.io/${{ github.actor }}/devstack:${{ env.DATESTAMP_VERSION }} \
                        .


            - name: Test that gdal imports
              run: docker run --rm ghcr.io/${{ github.actor }}/devstack:latest python -c "from osgeo import gdal"

            - name: Push docker
              run: |
                  docker push ghcr.io/${{ github.actor }}/devstack:latest
                  docker push ghcr.io/${{ github.actor }}/devstack:${{ env.DATESTAMP_VERSION }}

            - run: |
                docker run \
                    --rm \
                    --volume $(pwd):/tmp/devstack \
                    --workdir /tmp/devstack \
                    --privileged \
                    quay.io/singularity/singularity:v3.10.3 pull docker://ghcr.io/${{ github.actor }}/devstack:${{ env.DATESTAMP_VERSION }}

            - uses: actions/upload-artifact@v3
              with:
                  path: *.sif

