name: Build containers

on: [push]

defaults:
    run:
        shell: bash -l {0}

jobs:
    build:
        name: Build containers
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - name: login to GitHub Container Registry
              uses: docker/login-action@v1
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Build docker
              run: cd docker && docker build -t ghcr.io/${{ github.actor }}/natcap-devstack:latest

            - name: Push docker
              run: docker push  ghcr.io/${{ github.actor }}/natcap-devstack:latest

            - run: |
                docker run --privileged quay.io/singularity/singularity:v3.10.3 pull natcap-devstack.sif docker://ghcr.io/${{ github.actor }}/natcap-devstack:latest

            - uses: actions/upload-artifact@v2
              with:
                  path: natcap-devstack.sif

