name: Build containers

on: [push]

defaults:
    run:
        shell: bash -l {0}

jobs:
    build-docker:
        name: Build containers
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v2

            - name: Build and push
              uses: docker/build-push-action@v3
              with:
                  context: ./docker/
                  push: false
                  tags: ${{ github.repository }}:latest

            - run: |
                docker run --privileged quay.io/singularity/singularity:v3.10.3 pull natcap-devstack.sif docker://${{ github.repository }}:latest

            - uses: actions/upload-artifact@v2
              with:
                  path: natcap-devstack.sif

